on:
  push:
    tags:
      - 'v*'

name: Release


jobs:
  build:
    name: Create Release
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.x
          cache: true

      - run: dotnet restore
      - run: dotnet build --no-restore --configuration Release

      - run: gh release create ${{ github.ref_name }} --generate-notes './artifacts/bin/VrcOscLeash/release/VrcOscLeash.dll#VrcOscLeash.dll'
